server:
  # 服务器的HTTP端口，默认为8080
  port: 10202
  servlet:
    # 应用的访问路径
    context-path: /rest01


# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql8:3306/testdb01?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
